#!/bin/bash

USB="$(mount | grep '/dev/sdc')" #to detect usb

while [ true ]
do
	USB="$(mount | grep '/dev/sdc')"
	
	if [[ -z "$USB" ]]
	then
		echo "usb not detected"
	else

		echo "usb detected"
	
		if [[ -d ~/Desktop/usb_mnt ]]
		then
			echo "usb already mounted"
			ls ~/Desktop/usb_mnt
		else
			mkdir ~/Desktop/usb_mnt
			cd ~/Desktop
			sudo mount /dev/sdc1 usb_mnt  #mount usb
			echo "usb mounted"
			ls usb_mnt
		fi
	
			cd ~/Desktop/usb_mnt
			for i in $(seq 0 0)    # create text : message log
			do
				echo "Time and Date was created on: $(date +%D-%T)" >> message.txt
				echo "message created"
				ls ~/Desktop/usb_mnt
			done
	
		cd $OLDPWD
		cd ~/Desktop/
		sudo umount /dev/sdc1   #unmount usb
		rmdir ~/Desktop/usb_mnt
		echo "unmount successful"
	
	else
		echo "no usb detected"
	fi
done
